### ISSUE TITLE
Why this repo got so much stars?

### ISSUE THREAD

**Issue by abhiiinav6** [adamelmore/good-repo#3]
When i found out this repo, I thought this repo has collection of good repos from gihub. And after reading the readme and code I found that this project is just created with create-react-app and nothing else was added to it except a sunglass image.

**Comment by justks** [comment]
https://twitter.com/adamdotdev/status/1622642796812173322

**Comment by abhiiinav6** [comment]
I have retweeted the tweet, stared the repo, created an issue.  Is it means I have higher chance of winning? 😎 😁

**Comment by jschuur** [comment]
Not a bug. Works as intended. 🕶️
